package ca.yorku.dal;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.serverless.dal.DynamoDBAdapter;

@DynamoDBTable(tableName = "categories_table2")
public class Category {

    private String id;
    private String name;
    private static DynamoDBAdapter db_adapter;
    private final DynamoDBMapper mapper;
    
    public Category(){
        DynamoDBMapperConfig mapperConfig = DynamoDBMapperConfig.builder()
                .build();
        // get the db adapter
        this.db_adapter = DynamoDBAdapter.getInstance();
        // create the mapper with config
        this.mapper = this.db_adapter.createDbMapper(mapperConfig);
    }
    
    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public void save(){
        mapper.save(this);
    }
    
    public boolean delete(String id){
        Category category;
        category = get(id);
        if(category != null){
            mapper.delete(category);
            return true;
        }
        return false;
    }
}
